openapi: 3.0.3

info:
  version: 1.0.0
  title: Delivery API
  description: API to interact with delivery orders


paths:
  /v1/order:
    post:
      tags:
        - order
      summary: Add a new order
      description: Add a new order
      operationId: addOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId'
        '404':
          description: Invalid input

components:

  parameters:
    orderId:
      name: orderId
      in: query
      description: "order id"
      schema:
        type: integer
        minimum: 0

    latitude:
      name: latitude
      in: query
      description: "**latitude** where to deliver the order."
      schema:
        type: number
        minimum: -90
        maximum: 90

    longitude:
      name: longitude
      in: query
      description: "**longitude** where to deliver the order."
      schema:
        type: number
        minimum: -180
        maximum: 180

  schemas:
    Order:
      required:
        - orderId
        - latitude
        - longitude
      type: object
      properties:
        orderId:
          type: integer
          minimum: 0
          example: 1
        latitude:
          type: number
          minimum: -180
          maximum: 180
          example: 90.3131
        longitude:
          type: number
          minimum: -180
          maximum: 180
          example: -30.301

    OrderId:
      required:
        - orderId
      type: object
      properties:
        orderId:
          type: integer
          minimum: 0
          example: 1

