openapi: 3.0.3
info:
  title: Courier API
  version: 1.0.0
  description: API to interact with courier info

  #servers:
  # - url: https://url.ru/

paths:
  /v1/courier:
    get:
      summary: Get all information about a courier
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            description: Identifier for order
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourierInfo'
        '404':
          description: Courier not found
          content:
            application/json:
              schema:
                title: Courier not found
                type: string
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CourierInfo:
      type: object
      properties:
        id:
          type: integer
          description: Courier ID
        login:
          type: string
          description: Courier login
        orders_id:
          type: array
          items:
            type: integer
            minimum: 0
          description: Courier orders
      required:
        - id
        - login
        - orders_id
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          default: "Can't make response"
        err_code:
          type: integer
          minimum: 0
      required:
        - message
        - err_code