openapi: 3.0.3

info:
  version: 1.0.0
  title: Delivery API
  description: API to interact with delivery orders

paths:
  /v1/orders:
    get:
      operationId: getCouriers
      description: Get order ids.
      parameters:
        - name: limit
          in: query
          required: false
          description: Maximum number of orders in response.
          schema:
            type: integer
            minimum: 0
            default: 10

        - name: offset
          in: query
          required: false
          description: Number of orders to skip.
          schema:
            type: integer
            minimum: 0
            default: 0

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/OrderDto'

        '400':
          description: Wrong limit or offset parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    Coordinate:
      type: object
      properties:
        lon:
          type: number
          maximum: 180
          minimum: -180
          description: City geographic location (longitude)

        lat:
          type: number
          maximum: 90
          minimum: -90
          description: City geographic location (latitude)
      required:
        - lon
        - lat

    OrderDto:
      type: object
      properties:
        id:
          type: integer
        start:
          $ref: '#/components/schemas/Coordinate'
        finish:
          $ref: '#/components/schemas/Coordinate'
        status:
          type: string
          enum: [new, waiting, in_progress, done]

      required:
        - start
        - finish
        - status
        - id

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        err_code:
          type: integer
          minimum: 0
      required:
        - message
        - err_code
