openapi: 3.0.3

info:
  version: 1.0.0
  title: Delivery API
  description: API to interact with delivery orders

  #servers:
  # - url: https://url.ru/

paths:
  /v1/order:
    get:
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            description: Identifier for order

      responses:
        '200':
          description: Success. Information about order route.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'

        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Coordinate:
      type: object
      properties:
        lon:
          type: number
          maximum: 180
          minimum: -180
          description: City geographic location (longitude)

        lat:
          type: number
          maximum: 90
          minimum: -90
          description: City geographic location (latitude)
      required:
        - lon
        - lat

    GetOrderResponse:
      type: object
      properties:
        start:
          $ref: '#/components/schemas/Coordinate'
        finish:
          $ref: '#/components/schemas/Coordinate'
        status:
          type: string
          enum: [new, waiting, in_progress, done]

      required:
        - start
        - finish
        - status
        
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        err_code:
          type: integer
          minimum: 0
      required:
        - message
        - err_code
