openapi: 3.0.3
info:
  title: Authentication API
  description:
    API for register, login and logout users
  version: 1.0.0
#servers:
  #- url: https://url.ru/v1/
tags:
  - name: auth
    #description: 
paths:
  /v1/auth/register:
    post:
      tags:
        - auth
      summary: Creating a new user
      description: User registration in the service
      parameters:
        - in: header
          name: Register
          schema:
            $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Success responce
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse200'
        '400':
          description: Invalid input
          content:
            text/plain: #maybe json?
              schema:
                $ref: '#/components/schemas/PostResponse400'
        '409':
          description: Already exists
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PostResponse409'
components:
  schemas:
    UserType:
      type: string
      enum:
        - customer
        - courier
        - admin
      default: customer
      description: "type of user: customer, courier or admin"
    RegisterRequest:
      type: object
      properties:
        password:
          type: string
          format: password
        login:
          type: string
          description: unique user name
        userType:
          $ref: '#/components/schemas/UserType'
      required:
        - login
        - password
        - userType
    PostResponse200:
      title: Success response
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
          description: unique user name
        userType:
          $ref: '#/components/schemas/UserType'
      required:
        - id
        - login
        - userType
    PostResponse400:
      title: Invalid input
      type: string
      default: Invalid input
    PostResponse409:
      title: User already exists
      type: string
      default: User already exists
